[workspace]
resolver = "3"
default-members = ["marc21-cli"]
members = [ "marc21-*" ]

[workspace.package]
edition = "2024"
authors = ["Nico Wagner <n.wagner@dnb.de>"]
rust-version = "1.92"
license = "EUPL-1.2"

[workspace.dependencies]
marc21-record = { path = "./marc21-record" }
marc21-cli = { path = "./marc21-cli" }
