[package]
name = "marc21-cli"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[[bin]]
name = "marc21"
path = "src/main.rs"

[dependencies]
marc21-record = { workspace = true }
