# On Windows MSVC, statically link to the platform's standard C runtime
# ("CRT").
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
 
# On Linux MUSL target, Statically link to the platform's standard C
# runtime ("CRT") and produce a fully statically linked executable.
[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-self-contained=yes",
]

