[package]
name = "marc21-record"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[features]
default = ["performant"]
performant = ["winnow/simd"]

[dependencies]
bstr = { workspace = true }
flate2 = { workspace = true }
winnow = { workspace = true }

