name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '00 02 * * *'

permissions:
  contents: read
    
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - { os: ubuntu-latest, toolchain: stable, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: beta, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: nightly, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: "1.92", triple: x86_64-unknown-linux-gnu }
          - { os: windows-latest, toolchain: stable, triple: i686-pc-windows-msvc }
          - { os: macos-latest, toolchain: stable, triple: x86_64-apple-darwin }
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.target.toolchain }}
          targets: ${{ matrix.target.triple }}
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        if: ${{ matrix.target.toolchain != 'nightly' }}
        run: |
          cargo nextest run --workspace -F performant --no-fail-fast
          cargo test --doc --workspace -F performant --no-fail-fast
      - name: Run tests (nightly)
        if: ${{ matrix.target.toolchain == 'nightly' }}
        run: |
          cargo nextest run --workspace --all-features --no-fail-fast
          cargo test --doc --workspace --all-features --no-fail-fast
        
  fuzz:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 900
    strategy:
      matrix:
        item:
          - { name: byte-record, target: byte-record, max-total-time: 180 }
          - { name: tag-matcher, target: tag-matcher, max-total-time: 180 }
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/install@cargo-fuzz
      - run: |
          cargo fuzz run --jobs 2 ${{ matrix.item.target }} -- -max_total_time=${{ matrix.item.max-total-time }}
