name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '00 02 * * *'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - {os: ubuntu-latest, toolchain: stable, triple: x86_64-unknown-linux-gnu}
          - {os: ubuntu-latest, toolchain: beta, triple: x86_64-unknown-linux-gnu}
          - {os: ubuntu-latest, toolchain: nightly, triple: x86_64-unknown-linux-gnu}
          - {os: ubuntu-latest, toolchain: "1.93", triple: x86_64-unknown-linux-gnu}
          - {os: windows-latest, toolchain: stable, triple: i686-pc-windows-msvc}
          - {os: macos-latest, toolchain: stable, triple: x86_64-apple-darwin}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.target.toolchain }}
          targets: ${{ matrix.target.triple }}
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        if: ${{ matrix.target.toolchain != 'nightly' }}
        run: |
          cargo nextest run --workspace -F performant,serde --no-fail-fast
          cargo test --doc --workspace -F performant,serde --no-fail-fast
      - name: Run tests (nightly)
        if: ${{ matrix.target.toolchain == 'nightly' }}
        run: |
          cargo nextest run --workspace --all-features --no-fail-fast
          cargo test --doc --workspace --all-features --no-fail-fast

  fuzz:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 900
    strategy:
      matrix:
        item:
          - {target: record-matcher, max-total-time: 240}
          - {target: byte-record, max-total-time: 180}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/install@cargo-fuzz
      - run: |
          cargo fuzz run --jobs 2 ${{ matrix.item.target }} -- -max_total_time=${{ matrix.item.max-total-time }}

  clippy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: |
          cargo clippy --workspace --all-features

  rustfmt:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: |
          cargo fmt --all --check

  features:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-hack
      - name: "Check Powerset"
        run: |
          cargo hack check --workspace --features performant,nightly --no-dev-deps --ignore-unknown-features
      - name: "Test Powerset"
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cargo hack check --workspace --features performant,nightly --ignore-unknown-features

  deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - bans licenses sources
          - advisories
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@v6
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check ${{ matrix.checks }}
          arguments: --workspace --all-features
          command-arguments: -c .deny.toml
          rust-version: stable

  outdated:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/install@cargo-outdated
      - run: cargo update
      - run: |
          cargo outdated --workspace --root-deps-only --exit-code 1

  udeps:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install --locked cargo-udeps
      - run: cargo udeps --workspace

  dco:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - run: scripts/check-dco.sh

  typos:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - uses: crate-ci/typos@v1.42.1
        with:
          config: .typos.toml

  ci:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - clippy
      - dco
      - deny
      - features
      - fuzz
      - outdated
      - rustfmt
      - test
      - typos
      - udeps
    steps:
      - name: Check for cancelled jobs
        if: ${{ contains(needs.*.result, 'cancelled') }}
        run: |
          exit 1
      - name: Check for failed jobs
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |
          exit 1
      - name: Finish job
        run: |
          exit 0
